-- Create users table for login/auth (requires students and instructors to exist)
-- Run this if you get ORA-00942: table or view does not exist when creating students/instructors
-- Prerequisites: students, instructors tables must exist

create table users (
   user_id       number generated by default as identity primary key,
   email         varchar2(150) not null unique,
   password_hash varchar2(255) not null,
   role          varchar2(20) not null,
   student_id    number unique,
   instructor_id number unique,
   is_active     char(1) default 'Y' not null,
   created_at    date default sysdate not null,
   constraint chk_users_role
      check ( role in ( 'STUDENT',
                        'INSTRUCTOR',
                        'ADMIN' ) ),
   constraint chk_users_active check ( is_active in ( 'Y',
                                                      'N' ) ),
   constraint fk_users_student foreign key ( student_id )
      references students ( student_id ),
   constraint fk_users_instructor foreign key ( instructor_id )
      references instructors ( instructor_id ),
   constraint chk_users_role_owner
      check ( ( role = 'STUDENT'
         and student_id is not null
         and instructor_id is null )
          or ( role = 'INSTRUCTOR'
         and instructor_id is not null
         and student_id is null )
          or ( role = 'ADMIN'
         and student_id is null
         and instructor_id is null ) )
);
