create table students (
   student_id    number generated by default as identity primary key,
   first_name    varchar2(50) not null,
   last_name     varchar2(50) not null,
   email         varchar2(100) not null unique,
   phone         varchar2(20),
   date_of_birth date,
   registered_at date default sysdate,
   status        varchar2(20) default 'ACTIVE',
   constraint chk_student_status check ( status in ( 'ACTIVE',
                                                     'INACTIVE' ) )
);

create table instructors (
   instructor_id  number generated by default as identity primary key,
   first_name     varchar2(50) not null,
   last_name      varchar2(50) not null,
   email          varchar2(100) not null unique,
   phone          varchar2(20),
   specialization varchar2(100),
   hired_date     date default sysdate,
   status         varchar2(20) default 'ACTIVE',
   constraint chk_instructor_status check ( status in ( 'ACTIVE',
                                                        'INACTIVE' ) )
);

create table courses (
   course_id      number generated by default as identity primary key,
   instructor_id  number not null,
   course_title   varchar2(150) not null,
   description    varchar2(500),
   category       varchar2(100),
   fee            number(10,2) default 0,
   duration_weeks number,
   level_name     varchar2(20),
   status         varchar2(20) default 'ACTIVE',
   constraint fk_course_instructor foreign key ( instructor_id )
      references instructors ( instructor_id ),
   constraint chk_course_fee check ( fee >= 0 ),
   constraint chk_course_level
      check ( level_name in ( 'BEGINNER',
                              'INTERMEDIATE',
                              'ADVANCED' ) ),
   constraint chk_course_status check ( status in ( 'ACTIVE',
                                                    'INACTIVE' ) )
);

create table modules (
   module_id          number generated by default as identity primary key,
   course_id          number not null,
   module_title       varchar2(150) not null,
   module_description varchar2(500),
   module_order       number not null,
   duration_hours     number(5,2),
   constraint fk_module_course foreign key ( course_id )
      references courses ( course_id ),
   constraint uq_course_module_order unique ( course_id,
                                              module_order ),
   constraint chk_module_duration check ( duration_hours >= 0 )
);

create table enrollments (
   enrollment_id     number generated by default as identity primary key,
   student_id        number not null,
   course_id         number not null,
   enrollment_date   date default sysdate,
   completion_status varchar2(20) default 'ENROLLED',
   progress_percent  number(5,2) default 0,
   constraint fk_enrollment_student foreign key ( student_id )
      references students ( student_id ),
   constraint fk_enrollment_course foreign key ( course_id )
      references courses ( course_id ),
   constraint uq_student_course unique ( student_id,
                                         course_id ),
   constraint chk_completion_status
      check ( completion_status in ( 'ENROLLED',
                                     'IN_PROGRESS',
                                     'COMPLETED',
                                     'DROPPED' ) ),
   constraint chk_progress_percent
      check ( progress_percent >= 0
         and progress_percent <= 100 )
);

create table payments (
   payment_id     number generated by default as identity primary key,
   enrollment_id  number not null,
   amount         number(10,2) not null,
   payment_date   date default sysdate,
   payment_method varchar2(30),
   payment_status varchar2(20) default 'PENDING',
   constraint fk_payment_enrollment foreign key ( enrollment_id )
      references enrollments ( enrollment_id ),
   constraint chk_payment_amount check ( amount >= 0 ),
   constraint chk_payment_status
      check ( payment_status in ( 'PENDING',
                                  'PAID',
                                  'FAILED' ) )
);

create table certifications (
   certificate_id     number generated by default as identity primary key,
   enrollment_id      number not null unique,
   certificate_code   varchar2(50) not null unique,
   issue_date         date default sysdate,
   grade              varchar2(10),
   certificate_status varchar2(20) default 'ISSUED',
   constraint fk_certificate_enrollment foreign key ( enrollment_id )
      references enrollments ( enrollment_id ),
   constraint chk_certificate_status check ( certificate_status in ( 'ISSUED',
                                                                     'REVOKED' ) )
);

create table users (
   user_id       number generated by default as identity primary key,
   email         varchar2(150) not null unique,
   password_hash varchar2(255) not null,
   role          varchar2(20) not null,
   student_id    number unique,
   instructor_id number unique,
   is_active     char(1) default 'Y' not null,
   created_at    date default sysdate not null,
   constraint chk_users_role
      check ( role in ( 'STUDENT',
                        'INSTRUCTOR',
                        'ADMIN' ) ),
   constraint chk_users_active check ( is_active in ( 'Y',
                                                      'N' ) ),
   constraint fk_users_student foreign key ( student_id )
      references students ( student_id ),
   constraint fk_users_instructor foreign key ( instructor_id )
      references instructors ( instructor_id ),
   constraint chk_users_role_owner
      check ( ( role = 'STUDENT'
         and student_id is not null
         and instructor_id is null )
          or ( role = 'INSTRUCTOR'
         and instructor_id is not null
         and student_id is null )
          or ( role = 'ADMIN'
         and student_id is null
         and instructor_id is null ) )
);